version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastfood
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # This is for local development only, for the final delivery remove this service
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "9080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network

  # app:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile
  #   container_name: app
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_NAME: fastfood
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network

volumes:
  postgres_data:
  pgadmin-data:

networks:
  app-network: