apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    name: db-config
data:
  DB_HOST: fiap-fastfood.cre926gi33ka.us-east-1.rds.amazonaws.com
  DB_USERNAME: postgres
  DB_PASSWORD: fiapfastfood2025-postgres
  DB_NAME: postgres